# kubetpl:syntax:$
---
kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    stack: app
    app: app
spec:
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      stack: app
  template:
    metadata:
      labels:
        stack: app
        app: app
    spec:
      containers:
        - name: app
          image: $APP_IMAGE:$APP_TAG
          imagePullPolicy: $APP_IMAGE_PULL_POLICY
          ports:
            - containerPort: 8080
          # Add Secret Variables Here
          env:
            - name: TEST_VARIABLE
              value: $TEST_VARIABLE
          # Use the ConfigMap named here for general env
          envFrom:
            - configMapRef:
                name: stack-env
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
        - name: app2
          image: $APP_IMAGE:$APP_TAG
          imagePullPolicy: $APP_IMAGE_PULL_POLICY
          ports:
            - containerPort: 8080
          # Add Secret Variables Here
          env:
            - name: TEST_VARIABLE
              value: $TEST_VARIABLE
          # Use the ConfigMap named here for general env
          envFrom:
            - configMapRef:
                name: stack-env
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"