# kubetpl:syntax:$
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    stack: react-app
    app: backend
spec:
  selector:
    stack: react-app
    app: backend
  ports:
    - name: backend
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      stack: react-app
      app: backend
  template:
    metadata:
      labels:
        stack: react-app
        app: backend
    spec:
      containers:
        - name: app
          image: $BACKEND_IMAGE:$BACKEND_TAG
          imagePullPolicy: $BACKEND_PULL_POLICY
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: react-app-env
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: acr-service-principal