# kubetpl:syntax:$
kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    stack: react-app
    app: frontend
spec:
  type: LoadBalancer
  selector:
    stack: react-app
    app: frontend
  ports:
    - name: react-app
      protocol: TCP
      port: 31000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      stack: react-app
      app: frontend
  template:
    metadata:
      labels:
        stack: react-app
        app: frontend
    spec:
      # todo: get dev running as containerized version for alternative to telepresence flow
      containers:
        - name: frontend
          image: $FRONTEND_IMAGE:$FRONTEND_TAG
          imagePullPolicy: $FRONTEND_PULL_POLICY
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: react-app-env
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: acr-service-principal