context: ./containers
build_directory: ./containers
deployment_directory: ./deployments
components:
  - name: app
    requiredVariables:
      - PWD
      - HOME
    exposable: true
  - anotherApp
postgres_deployment: postgres
env_prefix: examples