context: ./containers
build_directory: ./containers
deployment_directory: ./deployments
stack: app
components:
  - name: config
    requiredVariables:
      - ENV
  - name: app
    requiredVariables:
      - PWD
      - HOME
    exposable: true
    containers:
      - dockerfile: ./containers/app/Dockerfile
        context: ./containers/app
        image: stack_app
postgres_deployment: postgres
env_prefix: examples