stack:
  name: app
environments:
  - name: local
    context: minikube
    activation:
      context: minikube
      env: ENV=local
  - name: ci
    context: minikube
    activation:
      context: minikube
      env: ENV=ci
  - name: stage
    context: platform-stg-blue
    activation:
      env: ENV=stage
components:
  - name: config
    requiredVariables:
      - ENV
    manifests:
      - ./deployments/config-local.env
  - name: app
    requiredVariables:
      - PWD
      - HOME
    exposable: true
    containers:
      - dockerfile: ./containers/app/Dockerfile
        context: ./containers/app
        image: stack-app
    manifests:
      - ./deployments/app.yaml
postgres_deployment: postgres
env_prefix: examples