context: ./containers
stack: app
components:
  - name: config
    requiredVariables:
      - ENV
    manifests:
      - ./deployments/config-local.env
  - name: app
    requiredVariables:
      - PWD
      - HOME
    exposable: true
    containers:
      - dockerfile: ./containers/app/Dockerfile
        context: ./containers/app
        image: stack_app
    manifests:
      - ./deployments/app.yaml
postgres_deployment: postgres
env_prefix: examples