stack:
  name: app
environments:
  - name: local
    activation:
      env: ENV=local
      context: docker-desktop || minikube || microk8s
  - name: ci
    activation:
      env: ENV=ci
      context: minikube
  - name: staging
    activation:
      env: ENV=staging
      context: platform-stg-blue
components:
  - name: config
    requiredVariables:
      - ENV
    manifests:
      - ./deployments/config.yaml
  - name: app
    exposable: true
    containers:
      - dockerfile: ./containers/app/Dockerfile
        context: ./containers/app
        image: stack-app
    manifests:
      - ./deployments/app.yaml
postgres_deployment: postgres
env_prefix: examples